services:
  web:
    build: ./
    # ports:
    #   - 5000:5000
    expose:
      - 5000
#     depends_on:
#       - db
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web

#   db:
#     image: postgres:13
#     volumes:
#       - postgres_data_prod:/var/lib/postgresql/data/
#     env_file:
#       - ./.env.prod.db

# volumes:
#   postgres_data_prod:
  